React Caption Project
ctokoli/react-capstone pull request #2
Opened 2023-08-12 17:39 UTC by ctokoli

These are the features implemented in this caption project. 

- The project is a single-page application (SPA) built with React and Redux and Covid 19 API.
- The data retrieved from the Covid-19 API was stored in the Redux store.
-  The data retrieved from the API was filtered.
- Every page (the main page and the pages for each item) have a unique route within the SPA.
- The project was deployed and it accessible online using [Render](https://render.com/).
- Added a link of the online version of the app to the README file.
- Created a unit tests for pure functions in the Redux code.
- Created integration tests for the application using the React Testing Library

2023-08-12 18:23 UTC, rotimiazeez requested changes
# Hi @ctokoli 👍🏽,
## Good job so far!
### To Highlight 👇🏽
- Good functioning app 👌🏽
- Good code structure 👏🏾
- Good use of Redux for state management 🙂
- Good application of filter stateless components for filtering data received from the API 🤝🏽
- Good job acknowledging the owner of the original design.
- No Linter error ✔️ 
- Good PR description 👍🏽 
- Good commit message(s) 😉
- Descriptive README 📖
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR WORDS>


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag (@rotimiazeez) me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

2023-08-12 18:23 UTC, rotimiazeez commented on README.md
Please ensure you add a link to a short video presentation of your project (not longer than 5mins) in your README file. Kindly ensure it contains a clear and objective description of the project in professional English. The topic and purpose of the project are made clear and contains a demo of the project, highlighting all the project features.

2023-08-12 18:23 UTC, rotimiazeez commented on src/App.css
>  }
Please ensure your design looks more like the original design from Behance, for a better UI.

Your Design  |  Behance Design
![Screenshot from 2023-08-12 19-06-19](https://github.com/ctokoli/react-capstone/assets/44624138/ea25ceca-d593-4d86-b565-488b4f935941)  |  ![Screenshot from 2023-08-12 19-08-23](https://github.com/ctokoli/react-capstone/assets/44624138/29c188f6-fff2-487e-a3cb-e03f9b1eee23)

2023-08-12 18:23 UTC, rotimiazeez commented on src/tests/__snapshots__/Components.test.js.snap
> +    </h5>
Kindly ensure all your app test cases are passing for a more professional codebase.
![Screenshot from 2023-08-12 19-05-26](https://github.com/ctokoli/react-capstone/assets/44624138/4217553f-91cf-4762-b85f-fb4061223ee7)

2023-08-12 23:53 UTC, Lizdev-05 requested changes
Hi @ctokoli , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

 ## Highlights
:heavy_check_mark: Professional Readme file :+1: 
:heavy_check_mark: Good commit history :+1:
:heavy_check_mark: No linter error :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-12 23:53 UTC, Lizdev-05 commented on README.md
> +- [Video ](https://drive.google.com/file/d/1gJdc3TPpkgGaqFrCs9_UFWwKBBZWQsVk/view?usp=sharing)
- [ ] As per the request of the previous reviewer, please create a brief video presentation of your project that is no longer than 5 minutes in duration. Your current presentation exceeds this time limit, so kindly record a new video that accurately showcases your project within the given time constraints. :relaxed:

2023-08-12 23:53 UTC, Lizdev-05 commented on src/App.css
> +  display: flex;
- [ ] The previous code reviewer has asked you to ensure that your app's home page matches the design that was given. However, upon comparing the two designs, it appears that the background colors of the countries' list should differ from each other, just like in the given design.

### Your design
![image](https://github.com/ctokoli/react-capstone/assets/73854999/2e915d2e-184e-4570-83cb-f54c7910bde1)

### Given design
![image](https://github.com/ctokoli/react-capstone/assets/73854999/a4ef6aa4-ed8d-45a6-8c11-926251dc3748)

2023-08-16 08:59 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Good Presentation Video ✔️ 
- The student deploys the application using Render✔️
- The project uses Redux for state management and data retrieved from the API are stored in the Redux store correctly✔️
- Followed [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-\(Free-PSDs\))✔️
- No Linter errors ✔️
-  App has unit tests for several components of the app and some pure functions in Redux code.✔️
- App has integration tests using React Testing Library ✔️


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-16 09:15 UTC, merged